### ISSUE TITLE
TWILIO_SID is not defined

### ISSUE THREAD

**Issue by mkscala** [christiannwamba/scotch-ng2-http#4]
ng2-http/server/dist/server.js:42
        this.twilioClient = (0, _twilio2.default)(TWILIO_SID, TWILIO_TOKEN);
                                                  ^

ReferenceError: TWILIO_SID is not defined
    at new Server (ng2-http/server/dist/server.js:42:51)
    at Object.<anonymous> (/Users/mkmani/a2-demos/ng2-http/server/dist/index.js:9:14)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! scotch-http-server@1.0.0 start: `npm run build && node ./dist/index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scotch-http-server@1.0.0 start script 'npm run build && node ./dist/index'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the scotch-http-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && node ./dist/index
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs scotch-http-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls scotch-http-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request

**Comment by adrianblade** [comment]
Is TWILIO_SID, TWILIO_TOKEN a environment variable?

**Comment by akmil** [comment]
I have same error on post new user. If remove `this.twilioClient.messages.create({....})` in scotch-ng2-http\server\server.js (line 79) all works fine
