### ISSUE TITLE
Error when creating a new message

### ISSUE THREAD

**Issue by dalamar66** [christiannwamba/scotch-ng2-http#8]
Hi,

I'm getting the following error when creating a new message: (Error on the server side)

node v6.9.1
npm  v3.10.8
tsc 2.0.10

> src\index.js -> dist\index.js
> src\server.js -> dist\server.js
> Server started: http://localhost:3000/
> C:\Users\SobradoD\Workspace\observablesTest\server\dist\server.js:107
>                         _this.twilioClient.messages.create({
>                                           ^
> 
> TypeError: Cannot read property 'messages' of undefined
>     at C:\Users\SobradoD\Workspace\observablesTest\server\dist\server.js:107:43
>     at FSReqWrap.oncomplete (fs.js:123:15)
> 
> npm ERR! Windows_NT 6.1.7601
> npm ERR! argv "C:\\Development\\nodejs\\node.exe" "C:\\Development\\nodejs\\nod
> _modules\\npm\\bin\\npm-cli.js" "start"
> npm ERR! node v6.9.1
> npm ERR! npm  v3.10.8
> npm ERR! code ELIFECYCLE
> npm ERR! scotch-http-server@1.0.0 start: `npm run build && node ./dist/index`

Could you please tell which versions are you using for node/npm/tsc?

**Comment by capcar** [comment]
@dalamar66, do you have resolved the problem? I have the same error: when I create a new message, I obtain this:
\scotch-ng2-http-master\server\dist\server.js:107
                        _this.twilioClient.messages.create({
                                          ^

TypeError: Cannot read property 'messages' of undefined
    at C:\Users\capizzi\Desktop\Sirsipa svn\03_ProgettiSviluppo\PROTOTIPO_FINALE\PrototipoInteg
rato_OR8\00_Lecce_v1\scotch-ng2-http-master\server\dist\server.js:107:43
    at FSReqWrap.oncomplete (fs.js:123:15)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\OPT\\nodejs\\node.exe" "C:\\Users\\capizzi\\AppData\\Roaming\\npm\\node_modu
les\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! scotch-http-server@1.0.0 start: `npm run build && node ./dist/index`
npm ERR! Exit status 1

**Comment by arthrmlo** [comment]
I've opened a PR that fixes this issue, please check #12
